name: App Python para testar Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Teste com pytest
      run: |
        pytest